### ISSUE TITLE
利用ss转发https出错

### ISSUE THREAD

**Issue by ee-5** [nondanee/UnblockNeteaseMusic#393]
为了使用分流代理、并在ios端quantumultx运行，我想按照[教程](https://desperadoj.com/17.html)使用“glider”转发为 Shadowsocks。

1.将app.js内端口修改为5138.
2.在宝塔面板ui界面，开放5138端口。
3.运行pm2 start UnblockNeteaseMusic/src/app.js --name="ios" -- -s -p 5138:5139 -o kuwo qq -e https://music.163.com

4.glider创建配置文件ios-ss.conf
verbose=True
listen=ss://chacha20-ietf-poly1305:password@:5320
forward=http://127.0.0.1:5318
5.通过 systemd 创建开机启动ios-ss.conf

但是运行后报错
[strategy] no available forwarders, just use: 127.0.0.1:5318, please check your settings or network

最后的结果是这一条ss ping不通。。利用quantumultx分流后无法使用。
感觉有可能是端口号搞错了？知识水平过于小白，困扰了半宿，烦请解答。

**Comment by nondanee** [comment]
我试了下，一样有这个提示
但好像不影响使用啊

![image](https://user-images.githubusercontent.com/26399680/74607313-ef0ba380-5112-11ea-9535-9809e1087630.png)

**Comment by ee-5** [comment]
1.vps是搬瓦工洛杉矶的机器(才意识到。。)，音源选择qq migu，请问可以吗？
2.请问我的5138、5139、5320这三个端口的设置有错误吗？
3.![image](https://user-images.githubusercontent.com/53551556/74635981-0c3b8300-51a2-11ea-953a-16396a8e5406.png)
教程里这一步“复制二进制文件”我没有做，直接在/etc/glider内创建了ios-ss.conf请问有影响吗？

最后出来的ss ping不通，反复安装了好几次也没明白是哪的错误。知识水平过于小白。。拜谢

**Comment by nondanee** [comment]
1. 应该不可以，你可以搭完自测下
2. 没问题
3. 没影响，只要 systemctl 里 ExecStart glider 的路径要写对就行了
4. 检查下防火墙 ipset 之类的东西有没有开放 5320 端口

**Comment by ee-5** [comment]
非常感谢您的回答，因为那篇教程里说海外ip也可以。。我打算重新买一个阿里云测试，再次感谢🙏。

**Comment by DOTA2mm** [comment]
我参照这个教程用glider转，iOS上网页能播没权限的，app上连排行榜什么的都加载不出来了。。
看了node服务的日志，区别是MITM > music.163.com (ssl)来自app的请求没有后面的(ssl)，不知道这是啥情况

**Comment by ssthptfpd** [comment]
[root@VM-12-7-centos ~]# systemctl status glider-https-ss.service
● glider-https-ss.service - Glider UnblockNeteaseMusic Shadowsocks Service for iOS & iPadOS
   Loaded: loaded (/etc/systemd/system/glider-https-ss.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2022-09-28 21:04:08 CST; 24s ago
 Main PID: 1002 (glider)
    Tasks: 7
   Memory: 10.4M
   CGroup: /system.slice/glider-https-ss.service
           └─1002 /usr/bin/glider -config /etc/glider/https-ss.conf

9月 28 21:04:08 VM-12-7-centos systemd[1]: Started Glider UnblockNeteaseMusic Shadowsocks Service for iOS & iPadOS.
9月 28 21:04:08 VM-12-7-centos glider[1002]: 2022/09/28 21:04:08 group.go:191: [group] main: only 1 forwarder found, ...ecking
9月 28 21:04:08 VM-12-7-centos glider[1002]: 2022/09/28 21:04:08 server.go:37: [ss] listening TCP on :30001
9月 28 21:04:08 VM-12-7-centos glider[1002]: 2022/09/28 21:04:08 server.go:95: [ss] listening UDP on :30001
Hint: Some lines were ellipsized, use -l to show in full.
这样子应该是正常转发了吧，可是在CLASH上面不通，在IOS上面通的，但是不能解锁。真心搞不懂是哪里不行了，VPS上面的端口都放行了，还是不行。
